### ISSUE TITLE
Months in filenames are 0-indexed

### ISSUE THREAD

**Issue by nstepien** [synap5e/obs-screenshot-plugin#13]
For example I've got a screenshot with the following filename:
```
2020-06-23_23-46-45.png
```
but I expect July to be `07` instead:
```
2020-07-23_23-46-45.png
```

It would be nice if this plugin would also respect the "Filename Formatting" setting, if that's possible.
![image](https://user-images.githubusercontent.com/567105/88378483-fd807a00-cd98-11ea-861c-08551cb796b9.png)

**Comment by synap5e** [comment]
Cheers, I'll fix it next time I do some work on this.
https://github.com/synap5e/obs-screenshot-plugin/blob/master/screenshot-filter.c#L697 needs `nowtime->tm_mon + 1`

**Comment by synap5e** [comment]
Fixed in #32
