### ISSUE TITLE
Support for uncompressed screenshots

### ISSUE THREAD

**Issue by cmdremily** [synap5e/obs-screenshot-plugin#16]
Hi, I would like to use the screenshot just captured in a scene that I'm instantly transitioning to as a live effect. For that reason I would like to save the screenshot as quickly as possible.

Would it be possible to support some uncompressed format that saves faster, e.g. bmp or tiff?

**Comment by synap5e** [comment]
Changing output format should not effect latency of the image, unless you are saving images at a very high frequency and the compression is overloading your CPU. When the timer/hotkey triggers, the current image is copied into a temporary storage and queued to be saved to the image format requested. 
How are you triggering the screenshot? Keep in mind that the timer mode takes the first screenshot *after* the timer elapses and not at 0 seconds.

If you still do want uncompressed, there is a "raw" mode which has no compression and minimal file headers - see https://github.com/synap5e/obs-screenshot-plugin#raw-output. If you have your own code for reading this or are loading it into an advanced image program this could work, but if you need something obs can read the filter would need some changes.

**Comment by cmdremily** [comment]
The games I'm playing are really CPU heavy so I'm fairly certain that going with e.g. BMP instead of PNG would help bring down the delay from the currently 500ms-ish range which is too long for my application. 

I'm triggering the screenshot with a key press, without timer.

I can't use the raw mode as the format is not supported by OBS image source. Ideally OBS image source would support shared memory buffers... through named pipes but I can't find a way to do that unfortunately...

**Comment by synap5e** [comment]
The following python code should decode the raw format and display a window containing the image in `C:\tmp\screenshot.raw`, and only update the image when that file changes. You can then create a window capture on the image it's presenting. 
Note you will need to update the width and height variables to correctly match the screen you are filtering - if they do not match it will not work.

```python
import cv2
import numpy as np
import os

IMAGE_PATH = 'C:/tmp/screenshot.raw'
IMAGE_WIDTH = 1920
IMAGE_HEIGHT = 1080
LINESIZE = int((IMAGE_WIDTH * 4) / 32 + 0.5) * 32

def main():
    cv2.imshow('image', np.zeros((IMAGE_HEIGHT, IMAGE_WIDTH, 3), dtype=np.uint8))

    last = None
    while True:
        kc = cv2.waitKey(100)
        if kc & 0xff == 27:  # esc
            break

        if not os.path.exists(IMAGE_PATH):
            continue

        mtime = os.path.getmtime(IMAGE_PATH)
        if not last or mtime > last:
            last = mtime
            with open(IMAGE_PATH, 'rb') as f:
                buf = f.read(IMAGE_HEIGHT * LINESIZE)
                try:
                    image = np.frombuffer(buf, dtype=np.uint8).reshape((IMAGE_HEIGHT, LINESIZE // 4, 4))[:, :IMAGE_WIDTH]
                except Exception as e:
                    print(e)
                else:
                    cv2.imshow('image', cv2.cvtColor(image, cv2.COLOR_RGBA2BGR))


if __name__ == '__main__':
    main()

```

**Comment by synap5e** [comment]
It's a pity OBS's media source is so limited. It's so close to letting me specify a working `rawvideo` media source, but lacks the ability to pass on the size to ffmpeg, which would otherwise be able to decode the raw image file for OBS.
