### ISSUE TITLE
Output to URL - duplicate base URL

### ISSUE THREAD

**Issue by pbaan93** [synap5e/obs-screenshot-plugin#18]
Hi, 
when I set the URL in the filter, it sets a correct URL.
When triggered it does a PUT to a wrong URL. It somehow duplicates the base of the URL.

LOG:
16:45:00.600: [screenshot-filter] Set destination=http://localhost:8000/api/cam/snapshot, 1
16:45:17.472: Settings changed (hotkeys)
16:45:17.472: ------------------------------------------------
16:45:21.662: [screenshot-filter] Got capture_key pressed for Screenshot Filter, id: 35, key: Screenshot Filter.Afbeelding.Screenshot Filter, pressed: 1
16:45:21.662: [screenshot-filter] Triggering capture
16:45:21.662: [screenshot-filter] Got capture_key pressed for Screenshot Filter, id: 40, key: Screenshot Filter.Afbeelding 2.Screenshot Filter, pressed: 1
16:45:21.662: [screenshot-filter] Triggering capture
16:45:21.746: [screenshot-filter] Failed to upload file to http:///localhost:8000/localhost:8000/api/cam/snapshot - 12007

**Comment by synap5e** [comment]
Fixed in #32
