### ISSUE TITLE
Output to directory

### ISSUE THREAD

**Issue by synap5e** [synap5e/obs-screenshot-plugin#2]
Allow images to be written to a directory with a dynamic (strftime) name, instead of always to the same file.

**Comment by panhartstuff** [comment]
Any updates to this? This would be an extremely useful feature

**Comment by synap5e** [comment]
I'm really busy at the moment, but this is something that I want to come back to...

**Comment by the100yengamer** [comment]
Any updates on this as well?

**Comment by r3sus** [comment]
https://github.com/mili-inch/obs-screenshot-plugin/commit/112ceba11e405172a6aa19eb2245ce0d41147341

**Comment by r3sus** [comment]
My honest attempts to compile the fork failed.
Could you please provide compile instructions or ready-to-use version?
It will be really appreciated.
Off-Scene: Planning to move from Bandicam to OBS, but missing screenshot with hotkey feature.
Thanks.

**Comment by synap5e** [comment]
I'm not sure if mili-inch's fork is ready (haven't checked - only saw it when you linked it), but the way I compile this is getting a working copy of obs-studio compiling then copying `obs-screenshot-plugin` to the `plugins/` directory and adding 
```
add_subdirectory(obs-screenshot-filter)
```
to the bottom of `plugins/CMakeLists.txt`
You can then build it as part of obs-studio itself.

It should also be possible to get an out-of-tree build working, but doing it this way you can piggyback on the instructions for how to compile obs-studio. 
https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions

**Comment by the100yengamer** [comment]
That is interesting. I have not idea how to compile, but if someone can make a easy way to implement this to OBS that would be great!

**Comment by synap5e** [comment]
Once mili-inch's change is ready I'll be happy to merge it and provide a built dll to download that you can just drag-and-drop to install.

**Comment by the100yengamer** [comment]
Awesome! Thank you
