### ISSUE TITLE
Opening the most recent screenshot in OBS

### ISSUE THREAD

**Issue by Adotis** [synap5e/obs-screenshot-plugin#23]
I have the screenshots getting saved to a folder as intended; however, I would like to then have the most recent screenshot show up as a source in my OBS. Is there a way I can have OBS select the most recent screenshot in the folder? Or perhaps have new screenshots overwrite the previous screenshot?

**Comment by synap5e** [comment]
"Output to file" should overwrite - I'm not sure if OBS will detect the file change (or can be configured to).

**Comment by Adotis** [comment]
I was trying to find a way to keep the old files so that they would not get overwritten. I ended up using a plug-in by Exeldro called “Directory watch media” which works perfectly!
