### ISSUE TITLE
Support for "Current Scene"

### ISSUE THREAD

**Issue by wwboynton** [synap5e/obs-screenshot-plugin#27]
Would be spiffy if there were a hotkey that would automatically grab a screenshot of the active scene.

**Comment by synap5e** [comment]
You can add the filter to the current scene 
![image](https://user-images.githubusercontent.com/2515062/152659040-211ee4d9-6021-457d-87a9-a0a818029f00.png)
and then you should be able to configure a hotkey.
If you have multiple scenes and add the filter to *each* scene (and no scene contains another scene) then I think the hotkey should just result in screenshotting the active scene.
