### ISSUE TITLE
Support hotkey instead of timer

### ISSUE THREAD

**Issue by synap5e** [synap5e/obs-screenshot-plugin#3]
Allow images to be written on a hotkey event instead of at a timer.
This should have a dropdown/checkbox to disable the slider and enable a hotkey selector (if possible). Should combo well with #2

**Comment by the100yengamer** [comment]
Are you going to add Hotkey function? I would really enjoy this plugin with hotkey.
I would like to take screenshot of my console gaming in OBS so I can use that to blog.

**Comment by authorleon** [comment]
Hello, is there any update with this please?

**Comment by synap5e** [comment]
Currently we are having an issue with getting the scene name to create a unique name for the hotkey.
https://github.com/mili-inch/obs-screenshot-plugin/commit/112ceba11e405172a6aa19eb2245ce0d41147341#commitcomment-39360247

I'm hoping to find some free time this week to spend some time looking for a solution.

**Comment by authorleon** [comment]
Excellent, well if I can do anything to help please let me know. Thank you.

**Comment by synap5e** [comment]
I'm gonna work on #6 then release 1.3 with builds containing this change

**Comment by synap5e** [comment]
If anyone would like to try [1.3.0rc1](https://github.com/synap5e/obs-screenshot-plugin/releases/tag/1.3.0rc1) ~~[1.3.0rc0](https://github.com/synap5e/obs-screenshot-plugin/releases/tag/1.3.0rc0)~~ and let me know if that works you, that would be appreciated. 

Thanks to @mili-inch for the work on this feature. If you are interested in the changes I made check out the commit message in da85a6f5. To further explain some of the changes to IDs and `obs_property_set_visible`s I wanted to ensure that existing users upgrading would have minimal impact. Users relying on the timer will still need to enable the timer checkbox on filters, but other settings should persist.

**Comment by synap5e** [comment]
And as soon as I release, I notice an issue 🙃 
Seems like hotkeys aren't always appearing after adding a filter...

**Comment by synap5e** [comment]
Ok, lets try again...
[1.3.0rc1](https://github.com/synap5e/obs-screenshot-plugin/releases/tag/1.3.0rc1)

**Comment by the100yengamer** [comment]
First of all, I want to thank everyone who contributed to this project! This is god send and I know so many obs users have been waiting for this plugin!

I have one question, so I was able to setup plugin and it is working great.
I am using streamdeck to trigger the hotkey and it works, but in my use case it causes little issue.

Lets say I have scene 1 and scene 2, I assigned hotkey for each scenes. Hotkey only works when scene is active. While I am in scene 1, If I trigger the hotkey to take screenshot of scene 2 it will not work. Is this something to do with my setup? or script side of things?

**Comment by synap5e** [comment]
Nothing can be done in the plugin AFAIK. Scenes in OBS only render if they are active.

I would recommend adding your `scene 2` as a source to `scene 1` and setting it's size to 0x0, or putting it behind another source. This way `scene 2` will render even when `scene 1` is active, and therefore the hotkey will work. 

Unfortunately you will not be able to add `scene 1` to `scene 2` as then each scene would reference each other. An alternative (if you need both scene's screenshot filters to be active at all times) would be to instead create `scene 3` and `scene 4` where each scene contains one of the primary scenes at full size, and the other at 0 size. This way you can switch between which scene appears visible, but both `scene 1` and `scene 2` will always be being rendered.
