### ISSUE TITLE
The screenshot is take from the source and not from the scene

### ISSUE THREAD

**Issue by eaides** [synap5e/obs-screenshot-plugin#30]
I have a source (screen) with some cut and repositioning; it is from a VR screen (2 eyes in the same screen) and I capture/stream only one half of the screen.
The screenshot however is for the physical screen (2 eyes) and not for the output (one eye only, half of the screen)

**Comment by synap5e** [comment]
Does it work to add the filter to the scene instead of the source? 
![image](https://user-images.githubusercontent.com/2515062/152659109-8491afe2-a934-4cd9-bf74-357ad72f6fa7.png)

**Comment by eaides** [comment]
Ups, my mistake...

It works perfectly putting the filter on the scene, not on the source...

Thanks very much

Ernesto N. Aides
Rishon Letzion - Israel

________________________________

**Comment by eaides** [comment]
My mistake as I wrote to Simon Pinfold
