### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by AdrianTudC** [synap5e/obs-screenshot-plugin#31]
I scoured the internet and I just can't find anything on how to install this plugin ? Can you add a couple of lines in your readme ?

**Comment by synap5e** [comment]
Good idea. Will update the readme.

To install the plugin copy the dll to
`C:\Program Files (x86)\OBS\plugins`
then (re)launch OBS

**Comment by AdrianTudC** [comment]
I found the guide about DLLs by googling, but there's no DLL in the repo. Should I rename the .c file to .dll ?

**Comment by synap5e** [comment]
https://github.com/synap5e/obs-screenshot-plugin/releases/tag/1.3.1
