### ISSUE TITLE
Support building the plugin through CI

### ISSUE THREAD

**Issue by synap5e** [synap5e/obs-screenshot-plugin#33]
It would be nice to support building the plugin through CI.

This would enable bugfixes/enhancements made e.g. through the github editor e.g. #32 to be landed much easier, help in cases where people are keen to contribute or tweak things but don't know how to build e.g. #25

It would also make tweaks like #22 trivial

https://github.com/obsproject/obs-plugintemplate appears to have OBS plugin building, so could be used as a base.

**Comment by synap5e** [comment]
Or just pull from the fork https://github.com/norihiro/obs-screenshot-plugin lol

**Comment by wkpark** [comment]
Please see https://github.com/synap5e/obs-screenshot-plugin/pull/37
(based on the obs-plugintemplate work.)
