### ISSUE TITLE
Filter not creating images when not in the filtered scene

### ISSUE THREAD

**Issue by RobertErobert** [synap5e/obs-screenshot-plugin#35]
I am using the obs websocket plugin to enable and disable the screenshot filters.
When i am in the scene, where the filter is set, everything works as expected. But if i am in an other scene, no output will be written to my disk.

I tried "to File" and "to Directory", same with timer and no timer.
I tried to include the scene into my other scenes, to see if it than work, but it doesn't :( 
I am on OBS 27.2.4 (64Bit) portable mode.
I am on Windows 11.
I set the filter directly on a scene.

**Comment by synap5e** [comment]
The scene has to be active to be rendered.

A trick you can do to make it work is to add the scene you want to capture to the other scenes as source and resize it to 0x0 pixels or drag it off the canvas so it isn't seen.
![image](https://user-images.githubusercontent.com/2515062/165884206-068c91f6-963d-40e7-85a2-dcf5537f44de.png)
