### ISSUE TITLE
New OBS 28 breaks plugin

### ISSUE THREAD

**Issue by erickwatson** [synap5e/obs-screenshot-plugin#36]
Just testing all the plugins I'm using in 27.2.3 and the current version of obs-screenshot-plugin (1.4.0) fails to load when running OBS 28.0.0-beta1.
Log file shows as follows:
17:55:58.757: LoadLibrary failed for '../../obs-plugins/64bit/obs-screenshot-filter.dll': The specified module could not be found.
17:55:58.757:  (126)
17:55:58.757: Module '../../obs-plugins/64bit/obs-screenshot-filter.dll' not loaded

Understand that 28 is a major shift, but just testing everything and mentioning where there are major faults. Works perfectly with 27, has been really fun to play with!

**Comment by eaides** [comment]
Also not recognized on non-beta 28.0.1 (new release of OBS)
Great utility, can not update my OBS till this will be fix

@erickwatson if you enter the pull request, you can download the artifacts that run OK in version 28:
https://github.com/wkpark/obs-screenshot-plugin/actions/runs/3002879478
you have the version for 64 bits and the 32 bits

**Comment by synap5e** [comment]
Fixed in #37
