### ISSUE TITLE
New release 1.5.2 executable 64 bits is detected as severe by windows defender

### ISSUE THREAD

**Issue by eaides** [synap5e/obs-screenshot-plugin#38]
Windows defender detects obs-screenshot-filter-1.5.2-windows-x64-Installer.exe
infected by: Trojan:Win32/Wacatac.H!ml
[Detected by Microsoft Defender Antivirus]
Anyway, the zip file looks safe, and also individual .dll and .pdb are safe by various online tests.
Can you check a look?

**Comment by synap5e** [comment]
Yeah looks like innoinstaller signatures have been added to AV databases. Unsure if it's really worth trying to play whack-a-mole with these issues I'll get trying to use inno...

**Comment by synap5e** [comment]
Removing the installers from the release for now

**Comment by eaides** [comment]
great!
Zip files are OK
