### ISSUE TITLE
Filter cannot output PNGs on OBS v24 (RC4)

### ISSUE THREAD

**Issue by Stealthii** [synap5e/obs-screenshot-plugin#5]
The current plugin still works on OBS v23, however, changes in OBS v24 seem to have broken PNG output. RAW output still works, but PNG output silently fails.

**Comment by synap5e** [comment]
Reproduced in 24.0.0

**Comment by synap5e** [comment]
PNG output is working again if I rebuild against OBS 24.
Updates release here https://github.com/synap5e/obs-screenshot-plugin/releases/tag/1.2.2
