### ISSUE TITLE
Be able to setup screenshot filter to source

### ISSUE THREAD

**Issue by the100yengamer** [synap5e/obs-screenshot-plugin#8]
I see that we can setup screenshot filter for scene, but sometimes I will have my webcam and game source together in scene. I want to have an option to only take screenshot of game source even I have my webcam in same scene.

**Comment by synap5e** [comment]
This should be supported by adding the filter to the source instead of the scene (and is indeed how I use it myself). 
![image](https://user-images.githubusercontent.com/2515062/83210424-efeeaf80-a1ae-11ea-85cb-2e80e707de9a.png)

Does that work for you?

**Comment by the100yengamer** [comment]
just checked. It works!
Thank you so much!!
