### ISSUE TITLE
Global Screen shot option & increment screen shot filename

### ISSUE THREAD

**Issue by authorleon** [synap5e/obs-screenshot-plugin#9]
Hello,

First of all, excellent work with the plug-in thus far. I have tested it and it seems to be working perfectly. Here are a few things I noticed and a few recommendations.

1. When you search for the hotkey you cannot find it, only when you type in scream in the search filter you can find it. I believe you have already commented this and to be fixed in the near future.

2. Question: what is the output format? is it PNG or JPEG please.

3. I have never dealt with the RAW images before, But at present I'm unable to open them. Do I need a special software?

4. Recommendations:
 - 4.1 - When the user saves the image to a file location, allow the option to increment the file number in order not to overwrite your existing image you have just saved. (MyImage 01, MyImage 02, MyImage 03 etc). **SOLVED - MY Mistake, I selected file, not folder**
- 4.2 - Global screenshot. Not quite sure how to explain this but here we go. Imagine you have five scenes, and you are switching between them during your stream. This means you would set up five filters and therefore have five hotkeys. I think it would be a good idea that you set up the filter once And that it takes a screen short of what ever scene you are on.

_I have just done some testing and I have seen that you can set up the filter many times and use the same hotkey and it only works on the active scene_ Maybe the request for 4.2 is redundant. 

Again thank you very much for your efforts. Much appreciated.

**Comment by synap5e** [comment]
Hey!
Thanks for the kind words.

---

> 1. When you search for the hotkey you cannot find it, only when you type in scream in the search filter you can find it. I believe you have already commented this and to be fixed in the near future.

If you are on *release candidate 0* then hotkeys might not work until OBS is reloaded, but on *release candidate 1* the hotkeys should appear at the bottom of the "misc" hotkeys. 
![image](https://user-images.githubusercontent.com/2515062/83260821-8a321000-a20e-11ea-960f-3d1e602f2b36.png)

I asked around on the OBS discord, and the methods for grouping hotkeys are not yet documented/public, so going to the bottom of the "misc" is the only option for now at least.
If that's not the issue you are having, let me know (I'm marking as `awaiting response` for this).

---

> 2. Question: what is the output format? is it PNG or JPEG please.

Files are png unless raw mode is selected, and should be suffixed with `.png`

---

> 3. I have never dealt with the RAW images before, But at present I'm unable to open them. Do I need a special software?

The RAW feature is more intended for other software that may want to use this plugin, and allows it to skip unnecessary encoding of the png just to need to decode it immediately. If you are using this plugin to record images for later use, you shouldn't need to worry about RAW mode.

To answer your question though; RAW images have no compression, and contain the "raw" image data, so a purely black image would be all `0`s, or a purely red each pixel would be `255 0 0 0` (red, green, blue, alpha). PNG in comparison contains a bunch of metadata such as the dimensions of the image and compresses the data. 

---

Regarding true global screenshot, I believe there is currently being worked on in OBS itself, although your discovery that the same hotkey can be used for multiple sources does allow this plugin to function as such, which is good to know.

**Comment by authorleon** [comment]
Hello. First of all thank you very much for the detailed reply.
You have covered absolutely everything and I have been testing it out. 
Just to share your little bit of my workflow so you get an idea.
Using your fantastic plug-in > The file is sent to a watch folder > The images processed in less than 10 seconds with a watermark > And then it is uploaded directly to discord As an instant screen capture of gameplay and funny moments. 

I have a side question, I have not tested this yet. However I think it's more than possible. I think you can set your plug-in filter more than once on one scene. Therefore I can use different hotkeys to capture the image. Why, one image would go to one watch folder and another image would go to another watch folder with different settings. Allowing for different moods when processing each image, different borders, different colour saturations and so on. 

Again thank you very much, and if you need someone to test anything else in the future, you can count on me because one of my jobs is actually to debug software and report accordingly. Thank you again.

**Comment by synap5e** [comment]
Yep, putting a filter on more than one scene/source with distinct destinations/hotkeys is certainly possible.

For your use case of *plugin* -> *folder* -> *program integrating with discord* you might actually find some benefit in the HTTP destination option. This way your program could simply expose a local http endpoint and the plugin could upload the image directly to your program instead of having to watch the filesystem.
If you are editing the screenshot automatically as soon as it is created then this could also match the use case of raw image mode, although it probably isn't worth optimizing if it's only screenshotting a few times a minute or less.
